"""empty message

Revision ID: 37180f351df8
Revises: 977d92bf42bb
Create Date: 2022-07-07 16:46:45.665167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37180f351df8'
down_revision = '977d92bf42bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
